### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by lpan**
:slightly_smiling_face:

### CODE REVIEW

**Review by davepagurek — APPROVED** [review]
👌

**Comment by lpan** [comment]
image
@davepagurek I can't merge it :stuck_out_tongue_closed_eyes:

**Comment by davepagurek** [comment]
oh woops. merged! Also: is that custom css?

**Comment by lpan** [comment]
it's probably from [octotree](https://github.com/buunguyen/octotree) :slightly_smiling_face:

**Pull request merged**
